# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QFileDialog
from PyQt5 import QtCore, QtGui, QtWidgets
import algo_main as algorithm

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 113)
        self.Export = QtWidgets.QPushButton(Dialog)
        self.Export.setGeometry(QtCore.QRect(60, 40, 151, 31))
        self.Export.setObjectName("Export")
        self.Export.clicked.connect(self.export_grades)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "End"))
        self.Export.setText(_translate("Dialog", "Export to CSV"))
    def export_grades(self):
        csv_filename=QFileDialog.getSaveFileName()
        if csv_filename[0]:
            algorithm.export_to_csv(self.MainWindow.student_grade,csv_filename[0])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
