# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import QTimer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import UI_main as main
from Warning_UI import Ui_Warning
import final_UI
import algo_main as algorithm
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 315)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.import_student = QtWidgets.QPushButton(self.centralwidget)
        self.import_student.setGeometry(QtCore.QRect(70, 250, 211, 41))
        self.import_student.setObjectName("import_student")
        self.list_student = QtWidgets.QListWidget(self.centralwidget)
        self.list_student.setGeometry(QtCore.QRect(50, 30, 256, 192))
        self.list_student.setObjectName("list_student")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.import_student.clicked.connect(self.browsefiles)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.filename = ("", "")
        self.MainWindow=MainWindow
    def browsefiles(self):
        filename = QFileDialog.getOpenFileName()
        if filename[0]:
            self.list_student.addItem(filename[0])
            self.student_file=filename[0]
            self.student_grade=algorithm.parse_student_file(self.student_file)
            QTimer.singleShot(7000, self.switch_to_final_ui)
        else:
            self.display_warning()
    def display_warning(self):
        self.warning_ui=Ui_Warning()
        self.Warning=QtWidgets.QDialog()
        self.warning_ui.setupUi(self.Warning)
        self.Warning.show()
    def switch_to_final_ui(self):
        self.final_ui=final_UI.Ui_Dialog()
        self.Diaglog=QtWidgets.QDialog()
        self.final_ui.setupUi(self.Diaglog)
        self.MainWindow.close()
        self.Diaglog.show()
    def file_name(self):
        if self.filename[0]:
            return self.filename[0]
        else:
            main.Open("warning")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student File"))
        self.import_student.setText(_translate("MainWindow", "Import"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
